name: Python Garage Solution Engineering EDA stacks
version: 0.1.0
description: Python event driven microservice
language: python
maintainers:
  - name: GSE Team
    email: boyerje@us.ibm.com
    github-id: jbcodeforce
default-template: default
license: Apache-2.0
